### ISSUE TITLE
Error running nichenet_seuratobj_aggregate on v5 Seurat obj

### ISSUE THREAD

**Issue by DomenicoSkyWalker89** [saeyslab/nichenetr#253]
Dear all,

while running nichenet analysis on my v5 seurat obj i got the following error:

Error in nichenet_seuratobj_aggregate(seurat_obj = FISM, receiver = "oligodendrocytes",  :

no slot of name "data" for this object of class "Assay5"

Could you help me?

Best,

Domenico

![image](https://github.com/saeyslab/nichenetr/assets/53559811/34e9fbbb-a0e1-43f1-8c25-862e38df92c8)

**Comment by csangara** [comment]
Could you try following the step-by-step analysis instead and see if you can run the vignette?
https://github.com/saeyslab/nichenetr/blob/master/vignettes/seurat_steps.md

In the meantime I'll try to fix the issue in the coming weeks.

**Comment by niksa01** [comment]
I have this same issue, any update?

**Comment by DomenicoSkyWalker89** [comment]
I followed the classical pipeline and it worked as always(as suggested by @csangara), so you can try with that.

**Comment by csangara** [comment]
I've implemented a fix for the wrapper functions now. Please update to v2.0.6 and let me know if there would be any issues. Note that the alias conversion function will not longer work for v5 objects.

**Comment by avpatel18** [comment]
Hey! I have the same issue on V5 Seurat object with nichenetr V2.0.6 version. It seems like you have fixed this two weeks ago but not sure why I am still getting error. Any help much appreciated!

**Comment by csangara** [comment]
@avpatel18 Is it the same error as above? Could you also provide your `sessionInfo()`?

**Comment by avpatel18** [comment]
@csangara thank you for getting back to me. I had some other dependency issue but after fixing that all working now.
